import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "dQw4w9WgXcQ",
    video_title: "Rick Astley - Never Gonna Give You Up (Official Video)",
    video_description: "The official video for 'Never Gonna Give You Up' by Rick Astley. Subscribe to the official Rick Astley YouTube channel.",
    tags: ["Music", "Pop", "80s", "Classic"],
    cover_image: "dQw4w9WgXcQ",
    publish_date: "2024-01-01",
    client_name: "RCA Records",
    client_image: "/companies/sl-logo.png",
    client_feedback: "Loved the audio quality and classic style of editing.",
    video_link: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "3:32",
    software_used: ["DaVinci Resolve"]
  },
  {
    id: "9bZkp7q19f0",
    video_title: "PSY - GANGNAM STYLE (강남스타일) M/V",
    video_description: "The official music video for Gangnam Style by PSY. Recorded and produced in Korea.",
    tags: ["K-Pop", "Music", "Dance", "Hits"],
    cover_image: "9bZkp7q19f0",
    publish_date: "2024-02-15",
    client_name: "YG Entertainment",
    client_image: "/companies/sl-logo.png",
    client_feedback: "Incredible energy and color grading!",
    video_link: "https://www.youtube.com/watch?v=9bZkp7q19f0",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "4:12",
    software_used: ["Davinci Resolve", "After Effects"]
  },
  {
    id: "jNQXAC9IVRw",
    video_title: "Me at the zoo",
    video_description: "The first video on YouTube. Uploaded by co-founder Jawed Karim.",
    tags: ["First Video", "History", "Zoo", "Elephant"],
    cover_image: "jNQXAC9IVRw",
    publish_date: "2024-03-10",
    client_name: "YouTube History",
    client_image: "/companies/growthleo.png",
    client_feedback: "Historic and simple.",
    video_link: "https://www.youtube.com/watch?v=jNQXAC9IVRw",
    project_images: [],
    category: ["Talking Head", "Animation"],
    duration: "0:19",
    software_used: ["Davinci Resolve"]
  },
  {
    id: "Kf82s57sMug",
    video_title: "Relaxing Lofi Beats - Study & Focus Mix",
    video_description: "Lofi hip hop beats to study, work, or relax to. Compiled from top independent producers.",
    tags: ["Lofi", "Beats", "Study", "Relaxing"],
    cover_image: "Kf82s57sMug",
    publish_date: "2024-04-05",
    client_name: "ChilledCow",
    client_image: "/companies/growthleo.png",
    client_feedback: "Perfect audio engineering and smooth looping visual animations.",
    video_link: "https://www.youtube.com/watch?v=Kf82s57sMug",
    project_images: [],
    category: ["Explainer", "Motion Graphics"],
    duration: "10:00",
    software_used: ["Davinci Resolve", "Premiere Pro"]
  },
  {
    id: "tgbNymZ7vqY",
    video_title: "The Muppets - Bohemian Rhapsody",
    video_description: "The Muppets' rendition of Queen's classic Bohemian Rhapsody. Featuring all your favorite Muppets.",
    tags: ["Muppets", "Queen", "Puppets", "Cover"],
    cover_image: "tgbNymZ7vqY",
    publish_date: "2024-05-20",
    client_name: "The Muppets Studio",
    client_image: "/companies/growthleo.png",
    client_feedback: "Outstanding multicam edit and puppet sync.",
    video_link: "https://www.youtube.com/watch?v=tgbNymZ7vqY",
    project_images: [],
    category: ["Promo", "Motion Graphics"],
    duration: "4:55",
    software_used: ["Davinci Resolve"]
  },
  {
    id: "V-_O7nl0Ii0",
    video_title: "Beautiful Nature - 4K Cinematic Relaxation",
    video_description: "Cinematic footage of beautiful natural landscapes around the world, filmed in high definition.",
    tags: ["Nature", "4K", "Relaxation", "Cinematic"],
    cover_image: "V-_O7nl0Ii0",
    publish_date: "2024-06-12",
    client_name: "Nature Channel",
    client_image: "/companies/edu-bridge-academy.jpg",
    client_feedback: "Stunning color grading and crisp visuals.",
    video_link: "https://www.youtube.com/watch?v=V-_O7nl0Ii0",
    project_images: [],
    category: ["Documentary", "Motion Graphics"],
    duration: "5:20",
    software_used: ["Davinci Resolve"]
  },
  {
    id: "5vK7F_Tz1Gg",
    video_title: "Satisfying Fluid Simulation",
    video_description: "Amazing 3D fluid simulation compilation with vibrant colors and physics.",
    tags: ["Fluid", "Simulation", "3D", "Satisfying", "Shorts"],
    cover_image: "5vK7F_Tz1Gg",
    publish_date: "2024-07-01",
    client_name: "3D Art Collective",
    client_image: "/companies/edu-bridge-academy.jpg",
    client_feedback: "The fluid animation rendering is top notch.",
    video_link: "https://youtube.com/shorts/5vK7F_Tz1Gg",
    project_images: [],
    category: ["Shorts", "Motion Graphics", "Explainer"],
    duration: "0:59",
    software_used: ["Blender", "After Effects"]
  },
  {
    id: "3pxlVn8Zix4",
    video_title: "Amazing Close-up Macro Photography",
    video_description: "Exploring the tiny details of everyday objects under a macro lens.",
    tags: ["Macro", "Photography", "Close-up", "Shorts"],
    cover_image: "3pxlVn8Zix4",
    publish_date: "2024-07-15",
    client_name: "Macro World",
    client_image: "/companies/impel-it.png",
    client_feedback: "Eye-catching short with great zoom edits.",
    video_link: "https://youtube.com/shorts/3pxlVn8Zix4",
    project_images: [],
    category: ["Shorts", "Promo"],
    duration: "0:45",
    software_used: ["Davinci Resolve"]
  }
];
